### ISSUE TITLE
요 방갑다리미꾸라지푸라기괴물

### ISSUE THREAD

**Issue by ghost** [SpaceDEVofficial/Taesiabot.py-rewrite#1]
이용목적: 관리용
깃헙 아이디: Heckerer
디스코드 닉네임(unknown#0000): ! 𝑯𝒆𝒄𝒌𝒆𝒓𝒆𝒓 !#8004
디스코드 ID(12345678): 549011691615158282

**Comment by popop098** [comment]
수락합니다.
그러나 이 소스를 사용후 꼭 같은 라이센스로 공개하셔야합니다.
